upx:
  - enabled: true
    goos: [linux]
    compress: best
    lzma: true

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags: >-
      -s -w
    flags:
      - -trimpath

release:
  github:
    owner: marianozunino
    name: code
  name_template: "{{.ProjectName}} v{{.Version}}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_Linux_x86_64
    files:
      - README.md
      - LICENSE
      - fuzzel.yaml
      - fzf.yaml
      - rofi.yaml

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^refactor:"